#!/usr/bin/env python

WHITE = 37
BLACK = 30
RED = 31
BROWN = 33
ORANGE = BROWN
YELLOW = ORANGE
GREEN = 32
BLUE = 34
CYAN = 36
MAGENTA = 35
DEFAULT = 39  # reset underline

WHITE_BG = WHITE + 10
BLACK_BG = BLACK + 10
RED_BG = RED + 10
BROWN_BG = BROWN + 10
ORANGE_BG = BROWN_BG
YELLOW_BG = ORANGE_BG
GREEN_BG = GREEN + 10
BLUE_BG = BLUE + 10
CYAN_BG = CYAN + 10
MAGENTA_BG = MAGENTA + 10
DEFAULT_BG = DEFAULT + 10

BOLD = 1
BOLD_OFF = 22
UNDERLINE = 4
UNDERLINE_OFF = 24
BLINK = 5
BLINK_OFF = 25
RESET = 0

